export type Category =
  | "tarayici"
  | "yazici"
  | "yazilim"
  | "kesici"
  | "seramik"
  | "yedek";

export interface Product {
  slug: string;
  name: string;
  brand: string;
  category: Category;
  image: string;
  /** true: koyu grafit zeminli premium fotoğraf (kartta kenardan kenara) */
  photo?: boolean;
  blurb: string;
  tags: string[];
  specs: Record<string, string>;
}

export const CATEGORY_LABELS: Record<Category, string> = {
  tarayici: "3D Tarayıcılar",
  yazici: "3D Yazıcılar",
  yazilim: "Yazılımlar",
  kesici: "Kesici Takımlar",
  seramik: "Teknik Seramikler",
  yedek: "Yedek Parça",
};

export const products: Product[] = [
  // ——— 3D Tarayıcılar (Shining 3D) ———
  {
    slug: "freescan-ue-pro-2",
    name: "FreeScan UE Pro 2",
    brand: "Shining 3D",
    category: "tarayici",
    image: "/images/freescan-ue-pro-2.png",
    blurb: "Metroloji sınıfı hassasiyette, fotogrametri entegrasyonlu el tipi lazer tarayıcı.",
    tags: ["El tipi", "Metroloji", "Lazer"],
    specs: { Hassasiyet: "0,02 mm'ye kadar", "Tarama modu": "Çoklu mavi lazer", Kullanım: "El tipi", Uygulama: "Kalite kontrol, tersine mühendislik" },
  },
  {
    slug: "freescan-trak-pro-2",
    name: "FreeScan Trak Pro 2",
    brand: "Shining 3D",
    category: "tarayici",
    image: "/images/freescan-trak-pro-2.png",
    blurb: "Optik takipli, markersız ölçüm yapabilen dinamik referanslı tarama sistemi.",
    tags: ["Optik takip", "Markersız", "Metroloji"],
    specs: { Hassasiyet: "Metroloji sınıfı", "Takip": "Optik dinamik referans", Kullanım: "Büyük parça ölçümü", Uygulama: "Otomotiv, havacılık" },
  },
  {
    slug: "freescan-trak-nova",
    name: "FreeScan Trak Nova",
    brand: "Shining 3D",
    category: "tarayici",
    image: "/images/freescan-trak-nova.png",
    blurb: "Markersız tarama yapabilen yeni nesil takipli 3D tarama çözümü.",
    tags: ["Optik takip", "Markersız"],
    specs: { "Takip": "Optik", "Marker ihtiyacı": "Yok", Uygulama: "Üretim hattı ölçümü" },
  },
  {
    slug: "freescan-combo",
    name: "FreeScan Combo",
    brand: "Shining 3D",
    category: "tarayici",
    image: "/images/freescan-combo.png",
    blurb: "Lazer ve yapılandırılmış ışığı tek gövdede birleştiren çok fonksiyonlu el tarayıcısı.",
    tags: ["El tipi", "Çok modlu"],
    specs: { "Tarama modu": "Lazer + yapılandırılmış ışık", Kullanım: "El tipi", Uygulama: "Genel amaçlı tarama" },
  },
  {
    slug: "einscan-hx",
    name: "EinScan HX",
    brand: "Shining 3D",
    category: "tarayici",
    image: "/images/einscan-hx.webp",
    blurb: "Hibrit LED + lazer teknolojisiyle hem hızlı hem detaylı tarama.",
    tags: ["El tipi", "Hibrit"],
    specs: { "Tarama modu": "LED + mavi lazer hibrit", Kullanım: "El tipi", Uygulama: "Tasarım, tersine mühendislik" },
  },
  {
    slug: "einscan-libre",
    name: "EinScan Libre",
    brand: "Shining 3D",
    category: "tarayici",
    image: "/images/einscan-libre.png",
    blurb: "Kablosuz, ekranlı ve tamamen mobil yeni nesil el tarayıcısı.",
    tags: ["El tipi", "Kablosuz"],
    specs: { Bağlantı: "Kablosuz, dahili ekran", Kullanım: "Sahada mobil tarama" },
  },
  {
    slug: "einscan-rigil",
    name: "EinScan Rigil",
    brand: "Shining 3D",
    category: "tarayici",
    image: "/images/einscan-rigil.png",
    blurb: "Dünyanın ilk çok fonksiyonlu, uzun menzilli el tipi tarama platformlarından.",
    tags: ["El tipi", "Uzun menzil"],
    specs: { "Tarama alanı": "Geniş hacim", Kullanım: "El tipi / sehpa", Uygulama: "Büyük parçalar" },
  },
  {
    slug: "autoscan-inspec-2",
    name: "AutoScan Inspec 2",
    brand: "Shining 3D",
    category: "tarayici",
    image: "/images/autoscan-inspec-2.png",
    blurb: "Küçük ve hassas parçalar için tam otomatik masaüstü ölçüm tarayıcısı.",
    tags: ["Masaüstü", "Otomatik", "Metroloji"],
    specs: { Hassasiyet: "Mikron seviyesi", Kullanım: "Masaüstü otomatik", Uygulama: "Kesici uç, dental, hassas parça" },
  },
  {
    slug: "optimscan-5m-plus",
    name: "OptimScan 5M Plus",
    brand: "Shining 3D",
    category: "tarayici",
    image: "/images/optimscan-5m-plus.png",
    blurb: "Endüstriyel kalite kontrol için yüksek çözünürlüklü optik ölçüm sistemi.",
    tags: ["Sabit sistem", "Metroloji"],
    specs: { Sensör: "5 MP", Kullanım: "Sabit / robot entegre", Uygulama: "Boyutsal kalite kontrol" },
  },
  {
    slug: "robotscan-e0505",
    name: "RobotScan E0505",
    brand: "Shining 3D",
    category: "tarayici",
    image: "/images/robotscan-e0505.png",
    blurb: "Robot koluna entegre, tam otomatik hat içi ölçüm ve denetim hücresi.",
    tags: ["Robotik", "Otomasyon", "Metroloji"],
    specs: { Entegrasyon: "6 eksen robot", Kullanım: "Hat içi otomatik denetim", Uygulama: "Seri üretim kalite kontrol" },
  },
  {
    slug: "transcan-c",
    name: "Transcan C",
    brand: "Shining 3D",
    category: "tarayici",
    image: "/images/transcan-c.png",
    blurb: "Renkli doku yakalayan yapılandırılmış ışıklı masaüstü tarayıcı.",
    tags: ["Masaüstü", "Renkli tarama"],
    specs: { "Doku": "Tam renkli", Kullanım: "Masaüstü", Uygulama: "Kültürel miras, tasarım, e-ticaret" },
  },

  // ——— 3D Yazıcılar (Sharebot) ———
  {
    slug: "sharebot-metal-one",
    name: "Sharebot Metal One",
    brand: "Sharebot",
    category: "yazici",
    image: "/images/sharebot-metal-one.jpg",
    blurb: "Kompakt sınıfta metal 3D baskıyı erişilebilir kılan SLM yazıcı.",
    tags: ["Metal", "SLM"],
    specs: { Teknoloji: "SLM (lazer metal ergitme)", Malzeme: "Metal tozları", Uygulama: "Fonksiyonel metal parça" },
  },
  {
    slug: "sharebot-q",
    name: "Sharebot Q",
    brand: "Sharebot",
    category: "yazici",
    image: "/images/sharebot-q.jpg",
    blurb: "Endüstriyel hassasiyette, kapalı kabinli profesyonel FDM yazıcı.",
    tags: ["FDM", "Endüstriyel"],
    specs: { Teknoloji: "FDM", Kabin: "Kapalı, ısıtmalı", Uygulama: "Fonksiyonel prototip" },
  },
  {
    slug: "sharebot-q-dual",
    name: "Sharebot Q Dual",
    brand: "Sharebot",
    category: "yazici",
    image: "/images/sharebot-q-dual.jpg",
    blurb: "Çift ekstruderli Q platformu — destek malzemesiyle karmaşık geometriler.",
    tags: ["FDM", "Çift ekstruder"],
    specs: { Teknoloji: "FDM, çift ekstruder", Uygulama: "Karmaşık geometri, çözünür destek" },
  },
  {
    slug: "sharebot-q-xxl",
    name: "Sharebot Q XXL",
    brand: "Sharebot",
    category: "yazici",
    image: "/images/sharebot-q-xxl.jpg",
    blurb: "Büyük hacimli parçalar için genişletilmiş Q serisi platform.",
    tags: ["FDM", "Büyük hacim"],
    specs: { Teknoloji: "FDM", "Baskı hacmi": "XXL sınıf", Uygulama: "Büyük prototip ve kalıp" },
  },
  {
    slug: "sharebot-xxl",
    name: "Sharebot XXL+",
    brand: "Sharebot",
    category: "yazici",
    image: "/images/sharebot-xxl.jpg",
    blurb: "Geniş tabla ve güçlü gövdeyle endüstriyel büyük parça üretimi.",
    tags: ["FDM", "Büyük hacim"],
    specs: { Teknoloji: "FDM", Uygulama: "Mimari maket, büyük parça" },
  },
  {
    slug: "sharebot-big",
    name: "Sharebot BIG",
    brand: "Sharebot",
    category: "yazici",
    image: "/images/sharebot-big.jpg",
    blurb: "Adı gibi: metrelik parçaları tek gövdede basan dev platform.",
    tags: ["FDM", "Büyük hacim"],
    specs: { Teknoloji: "FDM", "Baskı hacmi": "Metre sınıfı", Uygulama: "Seri üretim aparatı, büyük prototip" },
  },
  {
    slug: "sharebot-viking",
    name: "Sharebot Viking",
    brand: "Sharebot",
    category: "yazici",
    image: "/images/sharebot-viking.jpg",
    blurb: "Atölye şartlarına dayanıklı, pratik ve hızlı FDM iş atı.",
    tags: ["FDM"],
    specs: { Teknoloji: "FDM", Uygulama: "Atölye içi hızlı prototip" },
  },
  {
    slug: "sharebot-one",
    name: "Sharebot ONE",
    brand: "Sharebot",
    category: "yazici",
    image: "/images/sharebot-one.jpg",
    blurb: "Eğitim ve ofis kullanımı için kompakt, güvenilir giriş modeli.",
    tags: ["FDM", "Kompakt"],
    specs: { Teknoloji: "FDM", Uygulama: "Eğitim, konsept model" },
  },
  {
    slug: "sharebot-snow-white",
    name: "Sharebot Snow White",
    brand: "Sharebot",
    category: "yazici",
    image: "/images/sharebot-snow-white.png",
    blurb: "SLS toz teknolojisiyle desteksiz, fonksiyonel naylon parçalar.",
    tags: ["SLS", "Toz"],
    specs: { Teknoloji: "SLS", Malzeme: "PA naylon tozları", Uygulama: "Fonksiyonel son kullanım parçası" },
  },
  {
    slug: "sharebot-voyager",
    name: "Sharebot Voyager",
    brand: "Sharebot",
    category: "yazici",
    image: "/images/sharebot-voyager.jpg",
    blurb: "DLP reçine teknolojisiyle yüksek detaylı, pürüzsüz yüzeyler.",
    tags: ["DLP", "Reçine"],
    specs: { Teknoloji: "DLP", Malzeme: "Fotopolimer reçine", Uygulama: "Dental, kuyum, ince detay" },
  },
  {
    slug: "creator-3-pro",
    name: "Creator 3 Pro",
    brand: "Sharebot",
    category: "yazici",
    image: "/images/creator-3-pro.webp",
    blurb: "Bağımsız çift ekstruderli, çok yönlü profesyonel yazıcı.",
    tags: ["FDM", "Çift ekstruder"],
    specs: { Teknoloji: "FDM (IDEX)", Uygulama: "Prototip, çift malzeme" },
  },
  {
    slug: "creator-hs",
    name: "Creator HS",
    brand: "Sharebot",
    category: "yazici",
    image: "/images/creator-hs.webp",
    blurb: "Yüksek hızlı baskı için optimize edilmiş üretken platform.",
    tags: ["FDM", "Yüksek hız"],
    specs: { Teknoloji: "FDM, yüksek hız", Uygulama: "Hızlı iterasyon" },
  },
  {
    slug: "guider-3",
    name: "Guider 3",
    brand: "Sharebot",
    category: "yazici",
    image: "/images/guider-3.webp",
    blurb: "Endüstriyel güvenilirlikte, ağ bağlantılı akıllı FDM yazıcı.",
    tags: ["FDM", "Endüstriyel"],
    specs: { Teknoloji: "FDM", Bağlantı: "Wi-Fi / bulut", Uygulama: "Ofis ve atölye" },
  },

  // ——— Kesici Takımlar ———
  {
    slug: "cnmg-1204",
    name: "CNMG 1204 Karbür Insert",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/cnmg-1204.jpg",
    photo: true,
    blurb: "Tornalama operasyonları için talaş kırıcılı, kaplamalı karbür kesici uç.",
    tags: ["Tornalama", "Karbür"],
    specs: { Tip: "CNMG 1204", Malzeme: "Kaplamalı karbür", Uygulama: "Çelik ve döküm tornalama" },
  },
  {
    slug: "sngx-120716",
    name: "SNGX 120716 Seramik Insert",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/sngx-120716.jpg",
    photo: true,
    blurb: "Yüksek hız işleme için seramik esaslı frezeleme ucu.",
    tags: ["Frezeleme", "Seramik"],
    specs: { Tip: "SNGX 120716", Malzeme: "Teknik seramik", Uygulama: "Yüksek hızlı işleme" },
  },
  {
    slug: "wngx-080416",
    name: "WNGX 080416-E Insert",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/wngx-080416.jpg",
    photo: true,
    blurb: "Dayanıklı kesme kenarıyla zorlu malzemelerde uzun takım ömrü.",
    tags: ["Frezeleme"],
    specs: { Tip: "WNGX 080416-E", Uygulama: "Zorlu alaşımlar" },
  },
  {
    slug: "boru-capak-alma",
    name: "Boru Çapak Alma Takımı",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/boru-capak.jpg",
    photo: true,
    blurb: "Boru iç-dış çapaklarını tek operasyonda temizleyen özel takım.",
    tags: ["Özel takım", "Pirinç"],
    specs: { Malzeme: "Pirinç gövde", Uygulama: "Boru işleme hatları" },
  },
  {
    slug: "pah-kirma",
    name: "Pah Kırma Takımı",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/pah-kirma.jpg",
    photo: true,
    blurb: "Hassas kenar kırma ve pah operasyonları için özel üretim takım.",
    tags: ["Özel takım"],
    specs: { Uygulama: "Kenar pahı, hazırlık operasyonları" },
  },

  // ——— Yazılımlar (CAD-CAM & Ölçüm) ———
  {
    slug: "geomagic-design-x",
    name: "Geomagic Design X",
    brand: "Oqton",
    category: "yazilim",
    image: "/images/yazilim-cad.jpg",
    photo: true,
    blurb:
      "Tarama verisini parametrik CAD modeline dönüştüren tersine mühendislik yazılımı.",
    tags: ["Tersine mühendislik", "CAD"],
    specs: {
      Girdi: "Nokta bulutu / mesh",
      Çıktı: "Parametrik CAD (SolidWorks, NX, Inventor aktarımı)",
      Uygulama: "Tersine mühendislik",
    },
  },
  {
    slug: "geomagic-control-x",
    name: "Geomagic Control X",
    brand: "Oqton",
    category: "yazilim",
    image: "/images/yazilim-olcum.jpg",
    photo: true,
    blurb:
      "Tarama-CAD karşılaştırmalı, renk haritalı boyutsal kalite kontrol yazılımı.",
    tags: ["Kalite kontrol", "Metroloji"],
    specs: {
      Analiz: "CAD karşılaştırma, GD&T",
      Rapor: "Renk haritası + ölçüm raporu",
      Uygulama: "Boyutsal kalite kontrol",
    },
  },
  {
    slug: "geomagic-essentials",
    name: "Geomagic Essentials",
    brand: "Oqton",
    category: "yazilim",
    image: "/images/yazilim-mesh.jpg",
    photo: true,
    blurb:
      "Tarama sonrası veri temizleme ve mesh düzenleme için giriş seviyesi araç seti.",
    tags: ["Mesh düzenleme"],
    specs: {
      Kapsam: "Mesh temizleme, hizalama, basitleştirme",
      Uygulama: "Tarama sonrası hazırlık",
    },
  },
  {
    slug: "solid-edge-shining3d",
    name: "Solid Edge Shining 3D Edition",
    brand: "Siemens",
    category: "yazilim",
    image: "/images/yazilim-solid.jpg",
    photo: true,
    blurb:
      "Tarama verisiyle senkron çalışan, Shining 3D cihazlarıyla paket sunulan CAD çözümü.",
    tags: ["CAD", "Senkron modelleme"],
    specs: {
      Teknoloji: "Senkron + parametrik modelleme",
      Paket: "Shining 3D tarayıcılarla birlikte",
    },
  },
  {
    slug: "exmodel",
    name: "ExModel",
    brand: "Shining 3D",
    category: "yazilim",
    image: "/images/yazilim-surface.jpg",
    photo: true,
    blurb:
      "Tarama verisinden hızlı yüzey ve katı model üretimi için pratik dönüşüm aracı.",
    tags: ["Mesh → CAD"],
    specs: {
      Girdi: "Tarama mesh verisi",
      Çıktı: "Yüzey / katı model",
    },
  },

  // ——— Teknik Seramikler ———
  {
    slug: "yapisal-seramik-parcalar",
    name: "Yapısal Seramik Parçalar",
    brand: "Mitalon",
    category: "seramik",
    image: "/images/seramik-parcalar.jpg",
    photo: true,
    blurb:
      "İleri teknoloji kalıplama prosesiyle üretilen, aşınmaya ve yüksek sıcaklığa dayanıklı endüstriyel seramik parçalar.",
    tags: ["Alümina", "Aşınma direnci"],
    specs: {
      Malzeme: "Alümina / zirkonya esaslı",
      Üretim: "İleri teknoloji kalıplama + sinterleme",
      Uygulama: "Tekstil, makina, aşınma plakaları",
    },
  },

  // ——— Yedek Parça (Tekstil) ———
  {
    slug: "airjet-yedek-parca",
    name: "Airjet Dokuma Makinası Parçaları",
    brand: "Mitalon",
    category: "yedek",
    image: "/images/toyota-airjet-pro.jpg",
    photo: true,
    blurb:
      "Airjet dokuma makinaları için ölçüsel birebir, yerli üretim yedek parçalar.",
    tags: ["Tekstil", "Dokuma"],
    specs: {
      Makina: "Airjet dokuma tezgahları",
      Üretim: "Tersine mühendislik destekli yerli üretim",
    },
  },
  {
    slug: "tekstil-makina-parcalari",
    name: "Tekstil Makinası Yedek Parçaları",
    brand: "Mitalon",
    category: "yedek",
    image: "/images/tekstil-10-pro.jpg",
    photo: true,
    blurb:
      "Tekstil makinaları için hassas işlenmiş, uzun ömürlü yedek parça üretimi.",
    tags: ["Tekstil"],
    specs: {
      Kapsam: "Mekanik aşınma parçaları",
      Teslimat: "Stoktan veya siparişe özel üretim",
    },
  },
  {
    slug: "hassas-islenmis-parcalar",
    name: "Hassas İşlenmiş Özel Parçalar",
    brand: "Mitalon",
    category: "yedek",
    image: "/images/tekstil-12-pro.jpg",
    photo: true,
    blurb:
      "Numuneden veya teknik resimden, siparişe özel hassas parça üretimi.",
    tags: ["Özel üretim"],
    specs: {
      Girdi: "Numune parça veya teknik resim",
      Tolerans: "Hassas işleme sınıfı",
    },
  },

  // ——— Karbür Insert Uçlar (katalog genişletme) ———
  {
    slug: "dnmg-1104",
    name: "DNMG 110408-PM Karbür Insert",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/dnmg-1104.jpg",
    photo: true,
    blurb: "Orta talaş kaldırma operasyonları için 55° eşkenar dörtgen karbür uç.",
    tags: ["Tornalama", "Karbür"],
    specs: { Tip: "DNMG 110408-PM", Uygulama: "Genel tornalama" },
  },
  {
    slug: "dnmg-1504",
    name: "DNMG 150408 / 150412 Karbür Insert",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/dnmg-1504.jpg",
    photo: true,
    blurb: "İki köşe radyus seçeneğiyle dayanıklı DNMG serisi tornalama ucu.",
    tags: ["Tornalama", "Karbür"],
    specs: { Tip: "DNMG 1504 serisi", "Radyus seçenekleri": "0,8 / 1,2 mm" },
  },
  {
    slug: "snmg-1204",
    name: "SNMG 120412-KM Karbür Insert",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/snmg-1204.jpg",
    photo: true,
    blurb: "Kare formuyla sekiz kesici köşe sunan ekonomik tornalama ucu.",
    tags: ["Tornalama", "Karbür"],
    specs: { Tip: "SNMG 120412-KM", Avantaj: "Çok köşeli ekonomik kullanım" },
  },
  {
    slug: "snmx-0904",
    name: "SNMX 0904 Serisi Frezeleme Ucu",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/snmx-0904.jpg",
    photo: true,
    blurb: "090408 ve 090411 varyantlarıyla yüzey frezeleme için karbür uç.",
    tags: ["Frezeleme", "Karbür"],
    specs: { Tip: "SNMX 090408 / 090411", Uygulama: "Yüzey frezeleme" },
  },
  {
    slug: "snmx-120608",
    name: "SNMX 120608 KM252S Frezeleme Ucu",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/snmx-120608.jpg",
    photo: true,
    blurb: "KM252S kalitesinde, ağır yüzey frezeleme için güçlendirilmiş uç.",
    tags: ["Frezeleme", "Karbür"],
    specs: { Tip: "SNMX 120608", Kalite: "KM252S" },
  },
  {
    slug: "snmx-120612",
    name: "SNMX 120612 KM252S Frezeleme Ucu",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/snmx-120612.jpg",
    photo: true,
    blurb: "Geniş radyuslu varyantıyla zorlu frezeleme şartları için SNMX ucu.",
    tags: ["Frezeleme", "Karbür"],
    specs: { Tip: "SNMX 120612", Kalite: "KM252S" },
  },
  {
    slug: "wnmg-0804",
    name: "WNMG 080408-KM Karbür Insert",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/wnmg-0804.jpg",
    photo: true,
    blurb: "Trigon formuyla altı kesici köşe sunan çok yönlü tornalama ucu.",
    tags: ["Tornalama", "Karbür"],
    specs: { Tip: "WNMG 080408-KM", Avantaj: "6 kesici köşe" },
  },

  // ——— Seramik & CBN Insert Uçlar ———
  {
    slug: "cngx-120716",
    name: "MI-CNGX120716 Seramik Insert",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/cngx-120716.jpg",
    photo: true,
    blurb: "Yüksek hız işleme için CNGX formunda seramik kesici uç.",
    tags: ["Seramik", "Yüksek hız"],
    specs: { Tip: "MI-CNGX120716", Malzeme: "Teknik seramik" },
  },
  {
    slug: "rcgx-120700",
    name: "RCGX 120700 CBN Insert",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/rcgx-120700.jpg",
    photo: true,
    blurb: "Yuvarlak formlu CBN uç — sertleştirilmiş malzemelerde uzun ömür.",
    tags: ["CBN", "Sert işleme"],
    specs: { Tip: "RCGX 120700", Malzeme: "CBN (kübik bor nitrür)" },
  },
  {
    slug: "sngn-120716",
    name: "SNGN 120716 CBN Insert",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/sngn-120716.jpg",
    photo: true,
    blurb: "Kare formlu CBN uç — döküm ve sert tornalama operasyonları için.",
    tags: ["CBN", "Sert işleme"],
    specs: { Tip: "SNGN 120716", Uygulama: "Döküm / sert tornalama" },
  },
  {
    slug: "dokum-seramik-takim",
    name: "Döküm İşleme Seramik Takımlar",
    brand: "Mitalon",
    category: "kesici",
    image: "/images/dokum-seramik-takim.jpg",
    photo: true,
    blurb: "Döküm parça işleme hatları için seramik esaslı kesici takım grubu.",
    tags: ["Seramik", "Döküm"],
    specs: { Uygulama: "Döküm parça işleme", Malzeme: "Teknik seramik" },
  },

  // ——— Yedek Parça (ek kalemler) ———
  {
    slug: "dokuma-mekanik-parcalar",
    name: "Dokuma Makinası Mekanik Parçaları",
    brand: "Mitalon",
    category: "yedek",
    image: "/images/tekstil-11.jpg",
    blurb: "Dokuma tezgahları için hassas işlenmiş mekanik aktarma parçaları.",
    tags: ["Tekstil", "Dokuma"],
    specs: { Kapsam: "Mekanik aktarma elemanları", Üretim: "Yerli hassas imalat" },
  },
  {
    slug: "tekstil-asinma-parcalari",
    name: "Tekstil Makinası Aşınma Parçaları",
    brand: "Mitalon",
    category: "yedek",
    image: "/images/tekstil-13.jpg",
    blurb: "Sık değişen aşınma parçalarının stoklu ve siparişe özel üretimi.",
    tags: ["Tekstil"],
    specs: { Teslimat: "Stoktan veya siparişe özel", Uygulama: "Aşınma parçaları" },
  },
];

export const BRANDS = ["Shining 3D", "Sharebot", "Mitalon"] as const;

export function byCategory(cat: Category): Product[] {
  return products.filter((p) => p.category === cat);
}
